items:
  - Ronald Reagan
  - Mahatma Gandhi
  - Taylor Swift
  - spaghetti
  - kale
  - chocolate
  - dolphins
  - mosquitoes
  - golden retrievers
  - freedom
  - war
  - taxes
  - democracy
  - laptops
  - plastic bags
  - books
  - the ocean
  - traffic jams
  - sunshine
  - nuclear weapons
  - coffee
  - hospitals
  - spiders
  - music
  - climate change
